apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: InfluxDB
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: '15s'
      queryTimeout: '60s'
      httpMethod: 'POST'
    secureJsonData: {}
